# 사전 자료 2

본 자료는 LG AI CAMP의 `LG Vision Module3`를 위한 두번째 사전 자료입니다.

Pytorch를 사용하는 것에 아직 미숙함을 가지고 계실 분들을 위해 만들어본 자료입니다.

본 자료는 http://www.numpy.org/ 를 참고하여 만들었습니다.

In [1]:
import torch

In [2]:
data = torch.randn(2,3)

### Pytorch는 NumPy를 GPU의 사용을 용이하게 하는 tool이다.

In [3]:
print (data)
print (data*5)
print (data+data)
print (data.shape)
print (data.dtype)

tensor([[ 0.4702, -0.4447,  0.1563],
        [-0.2237, -0.3004, -0.2547]])
tensor([[ 2.3511, -2.2236,  0.7817],
        [-1.1186, -1.5018, -1.2735]])
tensor([[ 0.9404, -0.8894,  0.3127],
        [-0.4474, -0.6007, -0.5094]])
torch.Size([2, 3])
torch.float32


- Data를 생성하는 여러 방법

In [4]:
data = torch.zeros([2,4])
print (data)
data = torch.ones([2,4])
print (data)
data = torch.eye(4)
print (data)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


- list와 차이점 및 벡터 내적

In [5]:
lst1 = [1, 2]
lst2 = [3, 4]

tor1 = torch.tensor([1, 2])
tor2 = torch.tensor([3, 4])

print (lst1 + lst2)
print (tor1 + tor2)
print (tor1 * tor2)

print (sum(tor1 + tor2))
print (tor1.dot(tor2))
print (torch.matmul(tor1.view(1,-1), tor2)[0])

[1, 2, 3, 4]
tensor([4, 6])
tensor([3, 8])
tensor(10)
tensor(11)
tensor(11)


- 매트릭스의 곱 (Matrix Multiplication)

In [6]:
mat1 = torch.tensor([[2, 5, 8], [5, 3, 1]])
mat2 = torch.tensor([[3, 2], [5, 4], [7, 8]])
print (mat1)
print (mat2)
print (torch.matmul(mat1, mat2))

tensor([[2, 5, 8],
        [5, 3, 1]])
tensor([[3, 2],
        [5, 4],
        [7, 8]])
tensor([[87, 88],
        [37, 30]])


- 인덱싱 / 슬라이싱

In [7]:
data = torch.randn(4,3)
print (data)
print (data[2, :])
print (data[:, 1])
print (data[2][1])

tensor([[-0.5011,  0.1630,  0.8407],
        [-1.2758, -0.0138,  0.9657],
        [-0.3524,  0.3903,  0.9138],
        [ 0.1925,  0.4548,  0.3561]])
tensor([-0.3524,  0.3903,  0.9138])
tensor([ 0.1630, -0.0138,  0.3903,  0.4548])
tensor(0.3903)


- 기본적인 통계 관련 함수  

In [8]:
print (torch.sum(data))
print (torch.mean(data))
print (torch.var(data))
print (torch.std(data))
print ()
print (torch.sum(data).item())
print (torch.mean(data).item())
print (torch.var(data).item())
print (torch.std(data).item())

tensor(2.1337)
tensor(0.1778)
tensor(0.4225)
tensor(0.6500)

2.133742332458496
0.177811861038208
0.42252153158187866
0.6500165462493896


- Pytorch 조건문

In [9]:
print (torch.where(data>0, torch.ones(data.shape), torch.zeros(data.shape)))

tensor([[0., 1., 1.],
        [0., 0., 1.],
        [0., 1., 1.],
        [1., 1., 1.]])


- Numpy와 호환 

In [10]:
import numpy

In [11]:
a = torch.ones(5)
print (a)
b = a.numpy()
print (b)
a = torch.from_numpy(b)
print (a)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


### GPU의 사용

In [12]:
print (torch.cuda.is_available())
print (torch.cuda.device_count())

True
2


In [13]:
x = torch.tensor([1,1]).cuda()
print (x)
x = x.cpu()
print (x)

tensor([1, 1], device='cuda:0')
tensor([1, 1])


In [14]:
# Computational Graph
a = torch.tensor([2.], requires_grad = True)
b = torch.tensor([1.], requires_grad = True)
c = a + b
d = b + 1
e = c * d
print (a)
print (b)
print (c)
print (d)
print (e)

tensor([2.], requires_grad=True)
tensor([1.], requires_grad=True)
tensor([3.], grad_fn=<AddBackward0>)
tensor([2.], grad_fn=<AddBackward0>)
tensor([6.], grad_fn=<MulBackward0>)


In [15]:
print (a.data)
print (a.grad)
print (a.grad_fn)

tensor([2.])
None
None


In [16]:
e.backward(retain_graph=True) # gradient가 계산됨.

In [17]:
print (a.grad)
print (b.grad)
print (c.grad)
print (d.grad)
print (e.grad)

tensor([2.])
tensor([5.])
None
None
None


/home/taehyeon/anaconda3/lib/python3.7/site-packages/torch/tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


In [18]:
# Computational Graph
a = torch.tensor([2.], requires_grad = True)
b = torch.tensor([1.], requires_grad = True)
c = a + b
d = b + 1
e = c * d

c.retain_grad()
d.retain_grad()
e.retain_grad()

In [19]:
e.backward(retain_graph=True)

In [20]:
print (a.grad)
print (b.grad)
print (c.grad)
print (d.grad)
print (e.grad)

tensor([2.])
tensor([5.])
tensor([2.])
tensor([3.])
tensor([1.])


In [21]:
a.grad.zero_()
b.grad.zero_()
c.grad.zero_()
d.grad.zero_()
e.grad.zero_()

print (a.grad)
print (b.grad)
print (c.grad)
print (d.grad)
print (e.grad)

tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])


In [22]:
a = a.detach()
print (a.requires_grad)

False


In [23]:
import torch.nn as nn
import torch.optim as optim

In [24]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.act1 = nn.ReLU()
        self.pool1 = nn.MaxPool2d(2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.act2 = nn.ReLU()
        self.pool2 = nn.MaxPool2d(2)
        
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc_act1 = nn.ReLU()
        self.fc2 = nn.Linear(120, 84)
        self.fc_act2 = nn.ReLU()
        self.fc3 = nn.Linear(84, 10)
    
    def forward(self, x):
        # Max-pooling over a (2,2) window.
        x = self.pool1(self.act1(self.conv1(x)))
        x = self.pool2(self.act2(self.conv2(x)))
        x = x.view(x.shape[0], -1)
        x = self.fc_act1(self.fc1(x))
        x = self.fc_act2(self.fc2(x))
        out = self.fc3(x)
        
        return out

In [25]:
net = Net()
print (net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (act1): ReLU()
  (pool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (act2): ReLU()
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc_act1): ReLU()
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc_act2): ReLU()
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [26]:
params = list(net.parameters())
print (len(params))
print (params[0].size())

10
torch.Size([6, 1, 5, 5])


1. net instance에서 direct하게 접근

In [27]:
print (net.conv1.weight)

Parameter containing:
tensor([[[[ 0.0387,  0.1513, -0.0147,  0.1962,  0.1955],
          [-0.0260,  0.0193, -0.0515,  0.0075,  0.0304],
          [-0.1833, -0.0489,  0.0387,  0.1472,  0.1698],
          [-0.1144,  0.1277,  0.1011,  0.1764,  0.1072],
          [-0.0120, -0.0923, -0.0234,  0.0870,  0.0626]]],


        [[[ 0.1387,  0.0401, -0.0980, -0.1611,  0.1129],
          [ 0.0289, -0.0007, -0.0945, -0.1503,  0.1114],
          [ 0.0186,  0.1943,  0.0652, -0.1153,  0.0774],
          [ 0.1990, -0.1820,  0.0460,  0.0894,  0.1580],
          [-0.1412, -0.1211,  0.0461,  0.0071, -0.1149]]],


        [[[-0.0011,  0.1744,  0.0682,  0.0382, -0.1025],
          [-0.1173,  0.0529,  0.0178, -0.0819,  0.1056],
          [-0.0543, -0.1549, -0.0848, -0.1929, -0.1825],
          [-0.0309, -0.1547, -0.0529,  0.0718,  0.1072],
          [-0.1975, -0.0190, -0.1968,  0.0031, -0.0641]]],


        [[[ 0.1748, -0.1888, -0.0156, -0.1219,  0.0384],
          [ 0.1285, -0.1054, -0.1444,  0.1724, -0.0255

In [28]:
print (params[0])

Parameter containing:
tensor([[[[ 0.0387,  0.1513, -0.0147,  0.1962,  0.1955],
          [-0.0260,  0.0193, -0.0515,  0.0075,  0.0304],
          [-0.1833, -0.0489,  0.0387,  0.1472,  0.1698],
          [-0.1144,  0.1277,  0.1011,  0.1764,  0.1072],
          [-0.0120, -0.0923, -0.0234,  0.0870,  0.0626]]],


        [[[ 0.1387,  0.0401, -0.0980, -0.1611,  0.1129],
          [ 0.0289, -0.0007, -0.0945, -0.1503,  0.1114],
          [ 0.0186,  0.1943,  0.0652, -0.1153,  0.0774],
          [ 0.1990, -0.1820,  0.0460,  0.0894,  0.1580],
          [-0.1412, -0.1211,  0.0461,  0.0071, -0.1149]]],


        [[[-0.0011,  0.1744,  0.0682,  0.0382, -0.1025],
          [-0.1173,  0.0529,  0.0178, -0.0819,  0.1056],
          [-0.0543, -0.1549, -0.0848, -0.1929, -0.1825],
          [-0.0309, -0.1547, -0.0529,  0.0718,  0.1072],
          [-0.1975, -0.0190, -0.1968,  0.0031, -0.0641]]],


        [[[ 0.1748, -0.1888, -0.0156, -0.1219,  0.0384],
          [ 0.1285, -0.1054, -0.1444,  0.1724, -0.0255

In [29]:
batch_size = 10
input = torch.randn(batch_size, 1, 32, 32)
output = net(input)

target = torch.randn(batch_size, 10)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(1.1050, grad_fn=<MseLossBackward>)


In [42]:
net.zero_grad()

print ('conv1.bias.grad before backward')
print (net.conv1.bias.grad)

loss.backward()

print ('conv1.bias.grad after backward')
print (net.conv1.bias.grad)

conv1.bias.grad before backward
None
conv1.bias.grad after backward
tensor([-0.0025, -0.0003,  0.0020,  0.0048,  0.0058,  0.0038])


In [44]:
learning_rate = 0.01
for param in net.parameters():
    param.data.sub_(param.grad.data * learning_rate)

In [45]:
# Create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# In your training loop:
num_epochs = 100
for i in range(num_epochs):
    optimizer.zero_grad()
    output = net(input)
    loss = criterion(output, target)
    loss.backward() # Calculate the gradients
    optimizer.step()